"""empty message

Revision ID: 3161481dadee
Revises: 
Create Date: 2019-04-16 11:51:06.943694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3161481dadee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('is_deleted', sa.Integer(), server_default=sa.text("'2'"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'is_deleted')
    # ### end Alembic commands ###
