"""empty message

Revision ID: da1d05c90f23
Revises: 
Create Date: 2019-04-21 10:42:39.746111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1d05c90f23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mobile', sa.String(length=10), nullable=True),
    sa.Column('otp', sa.String(length=10), nullable=True),
    sa.Column('is_verified', sa.Integer(), server_default=sa.text('2'), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_login',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('mobile', sa.String(length=10), nullable=True),
    sa.Column('type', sa.Integer(), server_default=sa.text("'2'"), nullable=False),
    sa.Column('username', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=True),
    sa.Column('is_blocked', sa.Integer(), server_default=sa.text("'2'"), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('twitter', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), server_default=sa.text('"not now"'), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('lead_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('sub_category', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.Column('score', sa.String(length=244), nullable=True),
    sa.Column('features', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), server_default=sa.text("'2'"), nullable=False),
    sa.Column('is_deleted', sa.Integer(), server_default=sa.text("'2'"), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    op.drop_table('users')
    op.drop_table('user_login')
    op.drop_table('otp')
    # ### end Alembic commands ###
